sudo: false
language: rust

rust:
  - stable
  - nightly

script: |
  cargo build --bin ufi --verbose &&
  cargo build --bin prazi --verbose
  
matrix:
  allow_failures:
    - rust: nightly
  include:
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt --all -- --check
